apiVersion: v1
kind: Service
metadata:
  labels:
    app: mynginx
  name: mynginx
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mynginx
  type: NodePort